### PR TITLE
Set up Coveralls support

### PR DESCRIPTION
**Pull request by Stephan202**
- Enable Jacoco coverage analysis.
- Send the coverage analysis to Coveralls.
- Add a badge showing the coverage on `master`.

Note: this PR is on top of #10.

### CODE REVIEW

**Comment by Stephan202** [comment]
> Nice, should we specify in the README a standard for PR code coverage?

Good question. A hard value may be too strict, but perhaps something along the lines of:

> New code must be covered by tests. As a rule of thumb, overall test coverage should not decrease. (There are exceptions to this rule, e.g. when more code is deleted than added.)

**Comment by philleonard** [comment]
Yes, I like the sound of that!

**Comment by Stephan202** [comment]
Ack, will add that before merging this PR. :)

**Comment by Stephan202** [comment]
Rebased and added a commit.

**Pull request merged**
