### PR TITLE
Use the new built-in Travis CI `jdk` constants

### PR DESCRIPTION
**Pull request by Stephan202**
And while there, add OpenJDK 8 and OpenJDK 9.

### CODE REVIEW

**Comment by Stephan202** [comment]
Funny. The [push builds](https://travis-ci.org/PicnicSupermarket/reactive-support/builds/386075637) all passed, but the `openjdk-ea` entry of the [PR builds](https://travis-ci.org/PicnicSupermarket/reactive-support/builds/386075664) failed. Seems `openjdk-11-ea+15_linux-x64_bin.tar.gz` was deleted _just now_. (Retriggering the build gives the same result.)

@sormuras, should be expect the script to automatically pick up the next EA build once it becomes available? (And if so, in your experience, what's the average delay? :).)

**Comment by Stephan202** [comment]
Thanks for the rapid double-checking! We'll keep an eye on it :)

**Comment by sormuras** [comment]
Tried https://download.java.net/java/early_access/jdk11/16/GPL/openjdk-11-ea+16_linux-x64_bin.tar.gz ... and yes, that works. ✔️ 

When the HTML page of http://jdk.java.net/11/ is updated to **jdk-11-ea+16** ... restart the failed axis.

**Comment by Stephan202** [comment]
Indeed, cause this way the page itself is also effectively broken :thinking:.

**Comment by sormuras** [comment]
Contacted Dalibor from Oracle. He's trying to poke somebody who may help here.

In the meanwhile, we need to allow `ea` (`11`) builds to fail. 
https://github.com/junit-team/junit5/commit/d64f11b56c724d819d5f2c6d4529b18829fd45b1

Just after the integration in Travis. 😢 It worked like a charm for month now... first time I see this happen.

**Comment by sormuras** [comment]
_If you have difficulty downloading any of these files please contact jdk-ea-download-help_ww@oracle.com._

**Comment by Stephan202** [comment]
@sormuras do you plan to implement an AI which automatically sends such an email and pauses the build until receiving a reply? :laughing:

**Comment by sormuras** [comment]
🤣 

https://twitter.com/DonaldOJDK/status/1002226415415197696 **soon**™️

**Comment by sormuras** [comment]
It works like charm again. For now. :)

**Comment by Stephan202** [comment]
Yes! Thanks for raising the issue upstream :)

**Pull request merged**
